[package]
name = "Osechi"
version = "0.1.2"
edition = "2024"

[dependencies]
eframe = "0.33.3"
rayon = "1.1"
nokhwa = { version = "0.10", features = ["input-native"] }
num_cpus = "1.16"
rfd = "0.17.2"
chrono = "0.4.44"
openh264 = "0.9.3"
mp4 = "0.14.0"
image = "0.25.10"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["run-cargo-test", "run-cargo-clippy","run-cargo-fmt","run-cargo-check"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 'z'
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"