[package]
name = "osechi"
version = "0.0.1"
edition = "2024"

[dependencies]
eframe = "0.34.2"
rayon = "1.1"
nokhwa = { version = "0.10", features = ["input-native"] }

#ログ関連
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook","run-cargo-fmt"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 'z'
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
